### PR TITLE
pyinst.py: don't use UPX to pack vcruntime140.dll

### PR DESCRIPTION
**Pull request by jbruchon**
Originally in commit 7b400ac40b8e9ce5abaa6d0293fa9d4f017cf1f3 but
lost when make_win.bat was tossed out.

## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [ ] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [ ] [Searched](https://github.com/pukkandan/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [ ] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [ ] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Explanation of your *pull request* in arbitrary form goes here. Please make sure the description explains the purpose and effect of your *pull request* and is worded well enough to be understood. Provide as much context and examples as possible.

### CODE REVIEW

**Comment by pukkandan** [comment]
Ideally, this should have been made in `pyinst` as well when fixing it for `make_win`

**Comment by Jules-A** [comment]
Apparently this was already fixed in Pyinstaller in 4.2: https://github.com/pyinstaller/pyinstaller/pull/5382

**Comment by pukkandan** [comment]
Since there is no disadvantage in using this patch, we'll keep it anyway incase someone is using older version of pyinstaller

**Comment by Vangelis66** [comment]
> incase someone is using older version of pyinstaller

The official **32-bit** `yt-dlp` executable (**youtube-dlc_x86.exe**) built on **Python 3.4.4** is compiled with **pyinstaller==3.5** (the last version of it to support py3.4), so if you enable UPX compression in GitHub Actions/compile locally with py3.4+UPX, your quoted statement _may sound relevant_  at first; but **CPython 3.4.x** has been compiled with VS2010, so instead of `vcruntime140.dll` we have `msvcr100.dll`, which isn't CFG enabled!
Otherwise, if you're compiling on CPython >=**3.5** (VS2015+) and pyinstaller <= **4.1**, then yes, **you do need to exempt `vcruntime140.dll` from UPX compression**... 😄

**Comment by pukkandan** [comment]
Well, clearly @jbruchon has a use-case for it. Hence the PR both here and in dlc

**Comment by Jules-A** [comment]
Vangelis, it's possible they installed Pyinstaller a while ago and ignore / didn't see the message recommending an upgrade (easy to miss if you don't look at the console) so pukkandan is right, this is still needed for some people and doesn't cause any harm.

**Comment by jbruchon** [comment]
I installed Python and pyinstaller system-wide on my Windows machine some months ago, and my general update process for my copy of the program has been `git fetch upstream; git merge upstream/master; make_win.bat`. I do not read the README every single time I want to pull updates to a program via Git and I don't generally update dependencies (especially those installed system-wide) unless I have to do so. The fix is simple and (more importantly) affects absolutely no one adversely, so I don't understand why it's inspiring such extensive discussion.

**Comment by pukkandan** [comment]
> I don't understand why it's inspiring such extensive discussion

The fix has been applied. What is the problem for there being discussion about it? If anything, I welcome it.

> git fetch upstream; git merge upstream/master; make_win.bat

yt-dlp doesn't support `make_win.bat`. I recommend using 
    git fetch upstream; git reset --hard upstream/master; pyinst.py
assuming you don't do any development. This will ensure that you won't have any issues even if the branch has been force pushed

**Comment by jbruchon** [comment]
I switched to `pyinst.py` when the batch file vanished.

**Pull request merged**
